OBJS = $(wildcard src/*.cpp)
CC = g++
COMPILER_FLAGS = -Wall -pedantic -Wfatal-errors
LINKER_FLAGS = -lSDL2 -lSDL2_image
OBJ_NAME = Tatanga

all : $(OBJS)
	$(CC) $(OBJS) -o $(OBJ_NAME) $(COMPILER_FLAGS) $(LINKER_FLAGS)

clean :
	rm -f $(OBJ_NAME) src/*.o
